plugins {
    id 'java'
}

group = 'de.tim30531'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    filteringCharset = 'UTF-8'
}

jar {
    archiveBaseName = 'DeathKnightScreen-Paper-1.20.1'
    archiveVersion = project.version
}
